# Generated by Django 5.0.4 on 2024-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_suppliers_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='level',
            field=models.IntegerField(default='Empty', editable=False, verbose_name='Уровень'),
        ),
    ]
