# Generated by Django 5.0.4 on 2024-05-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_suppliers_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='debt_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Задолженность'),
        ),
    ]
