# Generated by Django 5.0.4 on 2024-05-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_suppliers_debt_to_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='street',
            field=models.CharField(max_length=100, verbose_name='Улица'),
        ),
    ]
